name: CI

on:
  push:
    branches:
      - master

env:
    CARGO_TERM_COLOR: always

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        id: toolchain
        with:
          toolchain: stable
          components: clippy
      - name: Cache workspace
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ steps.toolchain.outputs.cachekey }}
      - name: Check formatting
        run: |
          cargo fmt --check
      - name: Lint
        shell: bash
        run: |
          cargo clippy --locked --all-features --all-targets -- -D warnings
      - name: Test
        shell: bash
        run: |
          cargo test --locked --all-features
